# Generated by Django 5.0.1 on 2024-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green')], max_length=50, null=True, verbose_name='Manager'),
        ),
    ]
