# Generated by Django 5.0.1 on 2024-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Aaron Barnes', 'Aaron Barnes'), ('Jessica Most', 'Jessica Most')], max_length=50, null=True, verbose_name='Manager'),
        ),
    ]
