# Generated by Django 5.0.1 on 2024-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_alter_state_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='manager',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True, verbose_name='Manager'),
        ),
    ]
