# Generated by Django 5.0.1 on 2024-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_remove_state_fte_actual_remove_state_floater_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='FTE_est',
            field=models.IntegerField(blank=True, default=0, verbose_name='Est. FTE'),
        ),
    ]
