# Generated by Django 5.0.1 on 2024-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_abbrev', models.CharField(choices=[], max_length=25, null=True, verbose_name='State')),
                ('position', models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Of Counsel', 'Of Counsel'), ('Floater', 'Floater')], default='Full-Time', max_length=25, verbose_name='Position')),
                ('source', models.CharField(blank=True, choices=[('Indeed', 'Indeed'), ('Linked In', 'Linked In'), ('Recruiter', 'Recruiter'), ('Employee Referral', 'Employee Referral')], max_length=25, null=True, verbose_name='Recruitment Source')),
                ('employee_referral_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referral Employee')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('five_lakes_firm', models.BooleanField(default=True, verbose_name='Five Lakes Law Group')),
                ('huron_firm', models.BooleanField(default=False, verbose_name='Huron Law Group')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('initial_notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
