# Generated by Django 5.0.1 on 2024-01-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA')], max_length=25, null=True, verbose_name='State'),
        ),
    ]
