# Generated by Django 5.0.1 on 2024-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[(' ', ' ')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA')], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='interview1',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
    ]
