# Generated by Django 5.0.1 on 2024-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_alter_applicant_state_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA'), ('GA', 'GA'), ('Don Green', 'Don Green'), ('Don Green', 'Don Green')], max_length=25, null=True, verbose_name='State'),
        ),
    ]
