# Generated by Django 5.0.1 on 2024-01-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_remove_interview1_applicant_interview1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview1',
            name='id',
        ),
        migrations.AddField(
            model_name='interview1',
            name='applicant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruiting.applicant'),
            preserve_default=False,
        ),
    ]
