# Generated by Django 5.0.1 on 2024-01-27 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_alter_applicant_manager_alter_applicant_state_abbrev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview1',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruiting.applicant')),
                ('interview1_scheduled', models.BooleanField(default=False, verbose_name='First Interview is scheduled')),
                ('interview1_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='First Interview Date')),
                ('interviewer1_manager', models.CharField(choices=[('Aaron Barnes', 'Aaron Barnes'), ('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer')),
                ('interview1_completed', models.BooleanField(default=False, verbose_name='Five Lakes Law Group')),
                ('interview1_notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'First Interview',
                'verbose_name_plural': 'First Interview',
            },
        ),
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[('Aaron Barnes', 'Aaron Barnes'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA'), ('CT', 'CT'), ('GA', 'GA'), ('HI', 'HI'), ('ME', 'ME'), ('OR', 'OR'), ('WI', 'WI')], max_length=25, null=True, verbose_name='State'),
        ),
    ]
