# Generated by Django 5.0.1 on 2024-01-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_interview1_model_interview2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview1_model',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='interview1_model',
            name='interview1_completed',
        ),
        migrations.RemoveField(
            model_name='interview1_model',
            name='interview1_date',
        ),
        migrations.RemoveField(
            model_name='interview1_model',
            name='interview1_notes',
        ),
        migrations.RemoveField(
            model_name='interview1_model',
            name='interview1_scheduled',
        ),
        migrations.RemoveField(
            model_name='interview1_model',
            name='interviewer1_manager',
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Applicant', serialize=False, to='recruiting.applicant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interview1',
        ),
    ]
