# Generated by Django 5.0.1 on 2024-01-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_interview1_alter_applicant_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview1',
            name='interview1_completed',
            field=models.BooleanField(default=False, verbose_name='First Interview Completed'),
        ),
        migrations.AlterField(
            model_name='interview1',
            name='interview1_scheduled',
            field=models.BooleanField(default=False, verbose_name='First Interview Scheduled'),
        ),
        migrations.AlterField(
            model_name='interview1',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Aaron Barnes', 'Aaron Barnes'), ('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
    ]
