# Generated by Django 5.0.1 on 2024-01-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_alter_interview1_interview1_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview1',
            old_name='applicant',
            new_name='applicant_id',
        ),
    ]
