# Generated by Django 5.0.1 on 2024-01-30 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_remove_interview1_model_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview1_model',
            name='interview1_completed',
            field=models.BooleanField(default=False, verbose_name='First Interview Completed'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='interview1_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='First Interview Date'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='interview1_notes',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='interview1_scheduled',
            field=models.BooleanField(default=False, verbose_name='First Interview Scheduled'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='interview1_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Applicant id'),
        ),
    ]
