# Generated by Django 5.0.1 on 2024-01-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_rename_applicant_interview1_applicant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview1',
            old_name='applicant_id',
            new_name='id',
        ),
    ]
