# Generated by Django 5.0.1 on 2024-01-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_rename_applicant_id_interview1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview1',
            name='applicant_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='applicant_id'),
        ),
        migrations.AlterField(
            model_name='interview1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
