# Generated by Django 5.0.1 on 2024-01-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_interview1_model_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview1_model',
            name='applicant_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Applicant id'),
        ),
    ]
