# Generated by Django 5.0.1 on 2024-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0009_alter_interview1_model_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview1_model',
            name='decline_email_sent',
            field=models.BooleanField(default=False, verbose_name='Decline Email Sent'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='decline_to_continue',
            field=models.BooleanField(default=False, verbose_name='Decline to Continue'),
        ),
        migrations.AddField(
            model_name='interview1_model',
            name='retain_in_file',
            field=models.BooleanField(default=False, verbose_name='Retain in File'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA'), ('GA', 'GA'), ('SC', 'SC')], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='interview1_model',
            name='interview1_date',
            field=models.DateField(blank=True, null=True, verbose_name='First Interview Date'),
        ),
    ]
