# Generated by Django 5.0.1 on 2024-01-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0009_interview1_applicant_id_alter_interview1_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview1',
            name='id',
        ),
        migrations.AlterField(
            model_name='interview1',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruiting.applicant'),
        ),
    ]
