# Generated by Django 5.0.1 on 2024-01-28 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0010_remove_interview1_id_alter_interview1_applicant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='id',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_id',
            field=models.OneToOneField(default=18, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recruiting.applicant'),
        ),
    ]
