# Generated by Django 5.0.1 on 2024-01-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0010_interview1_model_decline_email_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview1_model',
            old_name='decline_to_continue',
            new_name='approve_to_continue',
        ),
    ]
