# Generated by Django 5.0.1 on 2024-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0011_remove_applicant_id_applicant_applicant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_id',
        ),
        migrations.AddField(
            model_name='applicant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
