# Generated by Django 5.0.1 on 2024-01-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0012_remove_applicant_applicant_id_applicant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview1',
            old_name='applicant_id',
            new_name='applicant',
        ),
    ]
