# Generated by Django 5.0.1 on 2024-01-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0012_alter_interview1_model_approve_to_continue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview1_model',
            old_name='approve_to_continue',
            new_name='approved_to_continue',
        ),
    ]
