# Generated by Django 5.0.1 on 2024-01-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0013_rename_approve_to_continue_interview1_model_approved_to_continue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview2_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField(blank=True, null=True, verbose_name='Applicant id')),
                ('interview2_scheduled', models.BooleanField(default=False, verbose_name='Second Interview Scheduled')),
                ('interview2_date', models.DateField(blank=True, null=True, verbose_name='Second Interview Date')),
                ('interviewer2_manager1', models.CharField(blank=True, choices=[('Don Green', 'Don Green')], max_length=25, null=True, verbose_name='Interviewer #1')),
                ('interview2_notes1', models.TextField(blank=True, max_length=255, null=True, verbose_name='Interviewer #1 Notes')),
                ('interviewer2_manager2', models.CharField(blank=True, choices=[('Don Green', 'Don Green')], max_length=25, null=True, verbose_name='Interviewer # 2')),
                ('interview2_notes2', models.TextField(blank=True, max_length=255, null=True, verbose_name='Interviewer # 2 Notes')),
                ('interview1_completed', models.BooleanField(default=False, verbose_name='Second Interview Completed')),
                ('approved_to_continue', models.BooleanField(default=False, verbose_name='Approved to Continue')),
                ('decline_email_sent', models.BooleanField(default=False, verbose_name='Decline Email Sent')),
                ('retain_in_file', models.BooleanField(default=False, verbose_name='Retain in File')),
            ],
            options={
                'verbose_name': 'Second Interview',
                'verbose_name_plural': 'Second Interview',
            },
        ),
        migrations.DeleteModel(
            name='Interview2',
        ),
    ]
