# Generated by Django 5.0.1 on 2024-01-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0014_interview2_model_delete_interview2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview2_model',
            old_name='interview1_completed',
            new_name='interview2_completed',
        ),
    ]
