# Generated by Django 5.0.1 on 2024-01-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0015_rename_interview1_completed_interview2_model_interview2_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview1_model',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager1',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most')], max_length=25, null=True, verbose_name='Interviewer #1'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager2',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most')], max_length=25, null=True, verbose_name='Interviewer # 2'),
        ),
    ]
