# Generated by Django 5.0.1 on 2024-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0016_alter_interview1_model_interviewer1_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='salary',
            field=models.CharField(default='80,000', max_length=10, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most')], default='', max_length=50, verbose_name='Manager'),
        ),
    ]
