# Generated by Django 5.0.1 on 2024-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0017_applicant_salary_alter_applicant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview1_model',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager1',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer #1'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager2',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer # 2'),
        ),
    ]
