# Generated by Django 5.0.1 on 2024-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0018_alter_interview1_model_interviewer1_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalStep_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField(blank=True, null=True, verbose_name='Applicant id')),
                ('applicant_withdrawn', models.BooleanField(default=False, verbose_name='Applicant Withdrawal from Consideration')),
                ('offer_letter_sent_charles', models.BooleanField(default=False, verbose_name='Offer Letter Drafted / Sent to Charles')),
                ('offer_letter_sent_applicant', models.BooleanField(default=False, verbose_name='Offer Letter Forwarded to Applicant')),
                ('offer_letter_email_date', models.DateField(blank=True, null=True, verbose_name='Offer Letter Email Date')),
                ('offer_accepted', models.BooleanField(default=False, verbose_name='Was Offer Accepted?')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Offer Letter Email Date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed and Ready for Onboarding')),
            ],
            options={
                'verbose_name': 'Final Applicant Steps',
                'verbose_name_plural': 'Final Applicant Steps',
            },
        ),
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager'),
        ),
    ]
