# Generated by Django 5.0.1 on 2024-01-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0020_alter_finalstep_model_offer_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
