# Generated by Django 5.0.1 on 2024-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0021_applicant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='step',
            field=models.CharField(choices=[('New Resume', 'New Resume'), ('Interview1', 'Interview1'), ('Interview2', 'Interview2'), ('Final', 'Final'), ('Open File', 'Open File')], default='new resume', max_length=25, null=True, verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active'),
        ),
    ]
