# Generated by Django 5.0.1 on 2024-02-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0022_applicant_step_alter_applicant_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='step',
        ),
    ]
