# Generated by Django 5.0.1 on 2024-02-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0024_applicant_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='step',
        ),
    ]
