# Generated by Django 5.0.1 on 2024-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0025_remove_applicant_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='step',
            field=models.CharField(choices=[('New Resume', 'New Resume'), ('Interview1', 'Interview1'), ('Interview2', 'Interview2'), ('Final', 'Final'), ('Open File', 'Open File')], default='New Resume', max_length=25, null=True, verbose_name='Step'),
        ),
    ]
