# Generated by Django 5.0.1 on 2024-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0026_applicant_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_manager', models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Search by Manager')),
                ('search_state', models.CharField(blank=True, choices=[('CA', 'CA'), ('GA', 'GA'), ('SC', 'SC')], max_length=25, null=True, verbose_name='Search by State')),
                ('search_step', models.CharField(blank=True, choices=[('New Resume', 'New Resume'), ('Interview1', 'Interview1'), ('Interview2', 'Interview2'), ('Final', 'Final'), ('Open File', 'Open File')], max_length=25, null=True, verbose_name='Search by Step')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
            },
        ),
    ]
