# Generated by Django 5.0.1 on 2024-02-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0027_search_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='search_model',
            name='search_state',
            field=models.CharField(blank=True, choices=[('CA', 'CA'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='Search by State'),
        ),
    ]
