# Generated by Django 5.0.1 on 2024-02-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0029_alter_applicant_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Application Date'),
        ),
    ]
