# Generated by Django 5.0.1 on 2024-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0030_applicant_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview1_model',
            name='interviewer1_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Kevin Zibolski', 'Kevin Zibolski'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager1',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Kevin Zibolski', 'Kevin Zibolski'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer #1'),
        ),
        migrations.AlterField(
            model_name='interview2_model',
            name='interviewer2_manager2',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Kevin Zibolski', 'Kevin Zibolski'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Interviewer # 2'),
        ),
        migrations.AlterField(
            model_name='search_model',
            name='search_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Kevin Zibolski', 'Kevin Zibolski'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Search by Manager'),
        ),
    ]
