# Generated by Django 5.0.1 on 2024-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0031_alter_interview1_model_interviewer1_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Kevin Zibolski', 'Kevin Zibolski'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[('CA', 'CA'), ('CT', 'CT'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='search_model',
            name='search_state',
            field=models.CharField(blank=True, choices=[('CA', 'CA'), ('CT', 'CT'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='Search by State'),
        ),
    ]
