# Generated by Django 5.0.1 on 2024-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0032_alter_applicant_manager_alter_applicant_state_abbrev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='manager',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state_abbrev',
            field=models.CharField(choices=[], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='search_model',
            name='search_state',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True, verbose_name='Search by State'),
        ),
    ]
