# Generated by Django 5.0.1 on 2024-02-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('state_abbrev', models.CharField(choices=[('CA', 'CA'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='State')),
                ('position', models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Of Counsel', 'Of Counsel'), ('Floater', 'Floater')], default='Full-Time', max_length=25, verbose_name='Position')),
                ('salary', models.CharField(default='80,000', max_length=10, verbose_name='Salary')),
                ('manager', models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('five_lakes_firm', models.BooleanField(default=True, verbose_name='Five Lakes Law Group')),
                ('huron_firm', models.BooleanField(default=False, verbose_name='Huron Law Group')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('start_date', models.DateField(max_length=255, null=True, verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
