# Generated by Django 5.0.1 on 2024-02-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Start Date'),
        ),
    ]
