# Generated by Django 5.0.1 on 2024-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='reviewer',
            field=models.CharField(choices=[('Don Green', 'Don Green')], max_length=50, null=True, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_abbrev',
            field=models.CharField(choices=[('GA', 'GA'), ('SC', 'SC')], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='decision_manager',
            field=models.CharField(choices=[('Don Green', 'Don Green')], max_length=50, null=True, verbose_name='Decision Manager'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(choices=[('Don Green', 'Don Green')], max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='search_attorneys_model',
            name='search_state',
            field=models.CharField(blank=True, choices=[('GA', 'GA'), ('SC', 'SC')], max_length=25, null=True, verbose_name='Search by State'),
        ),
    ]
