# Generated by Django 5.0.1 on 2024-02-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0002_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_complete',
            field=models.BooleanField(default=False, verbose_name='Onboarding Complete'),
        ),
    ]
