# Generated by Django 5.0.1 on 2024-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0002_alter_call_monitoring_model_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics_model',
            name='timeframe',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarter', 'Quarterly'), ('Annual', 'Annual')], max_length=25, null=True, verbose_name='Metric'),
        ),
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='02/22/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/22/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='02/22/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='metrics_model',
            name='metric',
            field=models.CharField(choices=[('Attrition Rate', 'Attrition Rate'), ('Bandwidth', 'Bandwidth'), ('Call Timeliness', 'Call Timeliness'), ('Review Completion', 'Review Completion'), ('EA Completion', 'EA Completion'), ('Pro Se Answer Reviews', 'Pro Se Answer Reviews'), ('Other', 'Other')], max_length=25, null=True, verbose_name='Metric'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/22/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='to_do_model',
            name='date',
            field=models.DateField(blank=True, default='02/22/2024', max_length=25, null=True, verbose_name='Date'),
        ),
    ]
