# Generated by Django 5.0.1 on 2024-02-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0003_employee_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_date', models.DateField(blank=True, default='02052024', max_length=25, null=True, verbose_name='Date')),
                ('document', models.FileField(blank=True, null=True, upload_to='QA/')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'Coaching and QA',
                'verbose_name_plural': 'Coaching and QA',
            },
        ),
    ]
