# Generated by Django 5.0.1 on 2024-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0003_metrics_model_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_model',
            name='timeframe',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarter', 'Quarterly'), ('Annual', 'Annual')], max_length=25, null=True, verbose_name='Timeframe'),
        ),
    ]
