# Generated by Django 5.0.1 on 2024-02-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0004_coaching_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10, null=True, verbose_name='Priority'),
        ),
    ]
