# Generated by Django 5.0.1 on 2024-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0004_alter_metrics_model_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Start Date'),
        ),
    ]
