# Generated by Django 5.0.1 on 2024-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0005_employee_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Attorneys_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_manager', models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Search by Manager')),
                ('search_state', models.CharField(blank=True, choices=[('CA', 'CA'), ('GA', 'GA'), ('OH', 'OH'), ('SC', 'SC')], max_length=25, null=True, verbose_name='Search by State')),
                ('search_priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=25, null=True, verbose_name='Search by Priority')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
            },
        ),
    ]
