# Generated by Django 5.0.1 on 2024-02-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0006_search_attorneys_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coaching_QA',
        ),
    ]
