# Generated by Django 5.0.1 on 2024-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0006_alter_metrics_model_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_model',
            name='metric',
            field=models.CharField(choices=[('Attrition Rate', 'Attrition Rate'), ('Bandwidth', 'Bandwidth'), ('Call Timeliness', 'Call Timeliness'), ('Missing Dispo Codes', 'Missing Dispo Codes'), ('Review Completion', 'Review Completion'), ('EA Completion', 'EA Completion'), ('Pro Se Answer Reviews', 'Pro Se Answer Reviews'), ('Other', 'Other')], max_length=25, null=True, verbose_name='Metric'),
        ),
    ]
