# Generated by Django 5.0.1 on 2024-02-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0007_delete_coaching_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Coaching and QA',
                'verbose_name_plural': 'Coaching and QA',
            },
        ),
    ]
