# Generated by Django 5.0.1 on 2024-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0007_alter_metrics_model_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='qa_note',
            field=models.TextField(blank=True, null=True, verbose_name='Coaching and QA Notes'),
        ),
    ]
