# Generated by Django 5.0.1 on 2024-02-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0008_qa_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='QA/'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='employee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qa_model',
            name='method',
            field=models.CharField(choices=[('Email', 'Email'), ('In Person', 'In Person'), ('Phone', 'Phone'), ('Teams', 'Teams')], max_length=25, null=True, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='qa_note',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Interviewer #1 Notes'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='qa_time',
            field=models.TimeField(blank=True, max_length=25, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='re_attorney',
            field=models.CharField(blank=True, default='Full-Time', max_length=255, null=True, verbose_name='Attorney'),
        ),
        migrations.AddField(
            model_name='qa_model',
            name='related_to',
            field=models.CharField(choices=[('Email', 'Email'), ('In Person', 'In Person'), ('Phone', 'Phone'), ('Teams', 'Teams')], max_length=25, null=True, verbose_name='Related To'),
        ),
    ]
