# Generated by Django 5.0.1 on 2024-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0008_alter_qa_model_qa_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='follow_up_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Follow-Up Notes'),
        ),
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes / Messages'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Call Notes'),
        ),
    ]
