# Generated by Django 5.0.1 on 2024-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0009_alter_attorney_notes_model_follow_up_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call_monitoring_model',
            name='call_url',
            field=models.URLField(blank=True, null=True, verbose_name='Call url'),
        ),
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='02/23/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/23/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='02/23/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/23/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='to_do_model',
            name='date',
            field=models.DateField(blank=True, default='02/23/2024', max_length=25, null=True, verbose_name='Date'),
        ),
    ]
