# Generated by Django 5.0.1 on 2024-02-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0009_qa_model_delivered_by_qa_model_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/05/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='related_to',
            field=models.CharField(choices=[('Attorney Tone', 'Attorney Tone'), ('Attrition', 'Attrition'), ('Calendar', 'Calendar'), ('Call Time', 'Call Time'), ('DS Benefit', 'DS Benefit'), ('DS Consider', 'DS Consider'), ('DS Not Loan', 'DS Not Loan'), ('EA', 'EA'), ('File Review', 'File Review'), ('Handling Work', 'Handling Work'), ('Identify Self / Comp', 'Identify Self / Comp'), ('Lawsuit', 'Lawsuit'), ('Offer', 'Offer'), ('Recording Disclaimer', 'Recording Disclaimer'), ('Sharpen', 'Sharpen'), ('Understand DS Process', 'Understand DS Process')], max_length=25, null=True, verbose_name='Related To'),
        ),
    ]
