# Generated by Django 5.0.1 on 2024-02-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0010_alter_qa_model_qa_date_alter_qa_model_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Delivered By'),
        ),
    ]
