# Generated by Django 5.0.1 on 2024-02-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0011_alter_qa_model_delivered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/06/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='re_attorney',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attorney'),
        ),
    ]
