# Generated by Django 5.0.1 on 2024-02-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0011_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_model',
            name='date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Date'),
        ),
    ]
