# Generated by Django 5.0.1 on 2024-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0012_alter_qa_model_qa_date_alter_qa_model_re_attorney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/07/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='re_attorney',
            field=models.CharField(choices=[('Arnie, Donny', 'Arnie, Donny'), ('Magallanez, Alice', 'Magallanez, Alice'), ('Graham, Krissy', 'Graham, Krissy')], max_length=255, null=True, verbose_name='Attorney'),
        ),
    ]
