# Generated by Django 5.0.1 on 2024-02-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0012_alter_to_do_model_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='02/26/2024', max_length=25, null=True, verbose_name='Review Date')),
                ('from_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='From (Name)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Messages')),
                ('document', models.FileField(blank=True, null=True, upload_to='Notes/')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Follow-up')),
                ('follow_up_notes', models.TextField(blank=True, null=True, verbose_name='Follow-Up Notes')),
                ('follow_up_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('employee_id', models.ForeignKey(blank=True, choices=[(27, 'Emily Bonds'), (36, 'Francisca Kanu-Oji'), (26, 'Jannine Mutterer'), (24, 'Kent "Clint" Kirkland'), (23, 'Kristina "Kristy" Pierce'), (25, 'Leah Petree-Angone'), (35, 'Maria "Tini" Bournakis'), (33, 'Marian Farrow Martin'), (38, 'Melissa Jarrell'), (28, 'Nakeyah Martin'), (30, 'Nichelle Sims'), (29, 'Randall "Randy" Carver'), (37, 'Richard "Ryan" Purvis'), (31, 'Samirah Hooks'), (34, 'Timothy Paschall')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issues Log',
                'verbose_name_plural': 'Issues Log',
            },
        ),
    ]
