# Generated by Django 5.0.1 on 2024-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0013_alter_qa_model_delivered_by_alter_qa_model_qa_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='re_attorney',
            field=models.CharField(choices=[('Arnie, Donny', 'Arnie, Donny'), ('Magallanez, Alice', 'Magallanez, Alice')], max_length=255, null=True, verbose_name='Attorney'),
        ),
    ]
