# Generated by Django 5.0.1 on 2024-02-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0013_issues_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues_model',
            name='notes',
        ),
        migrations.AddField(
            model_name='issues_model',
            name='issue',
            field=models.TextField(blank=True, null=True, verbose_name='Issue Description'),
        ),
    ]
