# Generated by Django 5.0.1 on 2024-02-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0014_alter_qa_model_re_attorney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_model',
            name='re_attorney',
        ),
    ]
