# Generated by Django 5.0.1 on 2024-02-27 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0014_remove_issues_model_notes_issues_model_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues_model',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='issues_model',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='issues_model',
            name='re_employee',
            field=models.ForeignKey(blank=True, choices=[(1, ' '), (27, 'Emily Bonds'), (36, 'Francisca Kanu-Oji'), (26, 'Jannine Mutterer'), (24, 'Kent "Clint" Kirkland'), (23, 'Kristina "Kristy" Pierce'), (25, 'Leah Petree-Angone'), (35, 'Maria "Tini" Bournakis'), (33, 'Marian Farrow Martin'), (38, 'Melissa Jarrell'), (28, 'Nakeyah Martin'), (30, 'Nichelle Sims'), (29, 'Randall "Randy" Carver'), (37, 'Richard "Ryan" Purvis'), (31, 'Samirah Hooks'), (34, 'Timothy Paschall')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
        ),
    ]
