# Generated by Django 5.0.1 on 2024-03-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0016_rename_re_employee_issues_model_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='03/08/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='call_url',
            field=models.URLField(blank=True, null=True, verbose_name='Call url (https://app.iz1.sharpen.cx/contactCard/)'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='03/08/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='disposition',
            field=models.CharField(choices=[('None', 'None'), ('Left Voicemail', 'Left Voicemail'), ('Incomplete Consult', 'Incomplete Consult'), ('Positive Consult', 'Positive Consult'), ('Credit Concerns', 'Credit Concerns'), ('Lawsuit Concerns', 'Lawsuit Concerns'), ('Requested Cancellation', 'Requested Cancellation'), ('Reconsidering Program', 'Reconsidering Program'), ('No Answer', 'No Answer'), ('Cancellation Prior to Consult', 'Cancellation Prior to Consult')], max_length=50, null=True, verbose_name='Disposition'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='03/08/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='date',
            field=models.DateField(blank=True, default='03/08/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='employee_id',
            field=models.ForeignKey(blank=True, choices=[(27, 'Emily Bonds'), (36, 'Francisca Kanu-Oji'), (26, 'Jannine Mutterer'), (24, 'Kent "Clint" Kirkland'), (23, 'Kristina "Kristy" Pierce'), (25, 'Leah Petree-Angone'), (35, 'Maria "Tini" Bournakis'), (33, 'Marian Farrow Martin'), (38, 'Melissa Jarrell'), (28, 'Nakeyah Martin'), (30, 'Nichelle Sims'), (29, 'Randall "Randy" Carver'), (37, 'Richard "Ryan" Purvis'), (31, 'Samirah Hooks'), (34, 'Timothy Paschall')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='03/08/2024', max_length=25, null=True, verbose_name='Date'),
        ),
    ]
