# Generated by Django 5.0.1 on 2024-02-07 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0017_hr_requests_model_delete_off_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Monitoring_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='02/07/2024', max_length=25, null=True, verbose_name='Date')),
                ('call_date', models.DateField(blank=True, default='02/07/2024', max_length=25, null=True, verbose_name='Call Date')),
                ('call_time', models.TimeField(blank=True, max_length=25, null=True, verbose_name='Call Time')),
                ('duration', models.CharField(max_length=25, null=True, verbose_name='Duration')),
                ('disposition', models.CharField(choices=[('None', 'None'), ('Left Voicemail', 'Left Voicemail'), ('Incomplete Consult', 'Incomplete Consult'), ('Credit Concerns', 'Credit Concerns'), ('Lawsuit Concerns', 'Lawsuit Concerns'), ('Requested Cancellation', 'Requested Cancellation'), ('No Answer', 'No Answer'), ('Cancellation Prior to Consult', 'Cancellation Prior to Consult')], max_length=50, null=True, verbose_name='Request Type')),
                ('document', models.FileField(blank=True, null=True, upload_to='HR/')),
                ('author', models.CharField(choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Decision Manager')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'Call Monitoring',
                'verbose_name_plural': 'Call Monitoring',
            },
        ),
    ]
