# Generated by Django 5.0.1 on 2024-09-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0017_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='09/24/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='09/24/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='09/24/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='date',
            field=models.DateField(blank=True, default='09/24/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='employee_id',
            field=models.ForeignKey(blank=True, choices=[(47, 'Bettie Carmack'), (27, 'Emily Bonds'), (36, 'Francisca Kanu-Oji'), (42, 'Jane Srivastava'), (26, 'Jannine Mutterer'), (24, 'Kent "Clint" Kirkland'), (23, 'Kristina "Kristy" Pierce'), (25, 'Leah Petree-Angone'), (35, 'Maria "Tini" Bournakis'), (33, 'Marian Farrow Martin'), (38, 'Melissa Jarrell'), (28, 'Nakeyah Martin'), (30, 'Nichelle Sims'), (29, 'Randall "Randy" Carver'), (37, 'Richard "Ryan" Purvis'), (31, 'Samirah Hooks'), (45, 'Teresa Stephens'), (34, 'Timothy Paschall'), (22, 'Wesley Tetsworth')], max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
        ),
        migrations.AlterField(
            model_name='metrics_model',
            name='metric',
            field=models.CharField(choices=[('Attrition Rate', 'Attrition Rate'), ('Quality Assurance', 'Quality Assurance'), ('Bandwidth', 'Bandwidth'), ('Call Timeliness', 'Call Timeliness'), ('Missing Dispo Codes', 'Missing Dispo Codes'), ('Review Completion', 'Review Completion'), ('EA Completion', 'EA Completion'), ('Pro Se Answer Reviews', 'Pro Se Answer Reviews'), ('Other', 'Other')], max_length=25, null=True, verbose_name='Metric'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='09/24/2024', max_length=25, null=True, verbose_name='Date'),
        ),
    ]
