# Generated by Django 5.0.1 on 2024-02-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0018_call_monitoring_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_monitoring_model',
            name='author',
        ),
        migrations.AddField(
            model_name='call_monitoring_model',
            name='reviewer',
            field=models.CharField(choices=[('Don Green', 'Don Green'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='disposition',
            field=models.CharField(choices=[('None', 'None'), ('Left Voicemail', 'Left Voicemail'), ('Incomplete Consult', 'Incomplete Consult'), ('Credit Concerns', 'Credit Concerns'), ('Lawsuit Concerns', 'Lawsuit Concerns'), ('Requested Cancellation', 'Requested Cancellation'), ('No Answer', 'No Answer'), ('Cancellation Prior to Consult', 'Cancellation Prior to Consult')], max_length=50, null=True, verbose_name='Disposition'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Calls/'),
        ),
    ]
