# Generated by Django 5.0.1 on 2024-02-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0020_call_monitoring_model_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/07/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='duration',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Duration'),
        ),
    ]
