# Generated by Django 5.0.1 on 2024-02-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0021_alter_call_monitoring_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='call_date',
            field=models.DateField(blank=True, default='02/08/2024', max_length=25, null=True, verbose_name='Call Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/08/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='02/08/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/08/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Attorney_Notes_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='02/08/2024', max_length=25, null=True, verbose_name='Review Date')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('follow_up_notes', models.BooleanField(default=False, verbose_name='Denied')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'Attorney Notes',
                'verbose_name_plural': 'Attorney Notes',
            },
        ),
    ]
