# Generated by Django 5.0.1 on 2024-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0023_attorney_notes_model_follow_up_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney_notes_model',
            name='from_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes / Messages'),
        ),
    ]
