# Generated by Django 5.0.1 on 2024-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0024_attorney_notes_model_from_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_model',
            name='qa_note',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Coaching and QA Notes'),
        ),
    ]
