# Generated by Django 5.0.1 on 2024-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0025_alter_qa_model_qa_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Call Notes'),
        ),
    ]
