# Generated by Django 5.0.1 on 2024-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0026_alter_call_monitoring_model_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney_notes_model',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Notes/'),
        ),
    ]
