# Generated by Django 5.0.1 on 2024-02-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0027_attorney_notes_model_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='Follow-up'),
        ),
    ]
