# Generated by Django 5.0.1 on 2024-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0028_alter_attorney_notes_model_follow_up_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='reviewer',
            field=models.CharField(choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='decision_manager',
            field=models.CharField(choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Decision Manager'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='search_attorneys_model',
            name='search_manager',
            field=models.CharField(blank=True, choices=[('Don Green', 'Don Green'), ('Eric Peterson', 'Eric Peterson'), ('Jessica Most', 'Jessica Most'), ('Matt Barnes', 'Matt Barnes')], max_length=25, null=True, verbose_name='Search by Manager'),
        ),
    ]
