# Generated by Django 5.0.1 on 2024-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0031_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_More_Model',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('address1', models.CharField(max_length=50, null=True, verbose_name='Address1')),
                ('address2', models.CharField(max_length=50, null=True, verbose_name='Address2')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('resident_state', models.CharField(max_length=5, null=True, verbose_name='State')),
                ('zip', models.CharField(max_length=25, null=True, verbose_name='Zip')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number2')),
                ('phone3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number3')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email2')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email3')),
                ('state_bar_number', models.CharField(max_length=25, null=True, verbose_name='Zip')),
                ('other_states', models.CharField(max_length=25, null=True, verbose_name='Zip')),
            ],
            options={
                'verbose_name': "Employee's Additional Data",
                'verbose_name_plural': "Employees' Additional Data",
            },
        ),
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='02/13/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='call_date',
            field=models.DateField(blank=True, default='02/13/2024', max_length=25, null=True, verbose_name='Call Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/13/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='02/13/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/13/2024', max_length=25, null=True, verbose_name='Date'),
        ),
    ]
