# Generated by Django 5.0.1 on 2024-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0032_employee_more_model_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_more_model',
            name='state_bar_document',
            field=models.FileField(blank=True, null=True, upload_to='Bar/'),
        ),
    ]
