# Generated by Django 5.0.1 on 2024-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0033_employee_more_model_state_bar_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_more_model',
            name='address1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address1'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='other_states',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Other States'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='resident_state',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='state_bar_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='State Bar Number'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='zip',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Zip'),
        ),
    ]
