# Generated by Django 5.0.1 on 2024-02-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0034_alter_employee_more_model_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_more_model',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
        ),
    ]
