# Generated by Django 5.0.1 on 2024-02-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0036_alter_employee_more_model_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_more_model',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee'),
        ),
    ]
