# Generated by Django 5.0.1 on 2024-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0037_alter_employee_more_model_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_more_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
