# Generated by Django 5.0.1 on 2024-02-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0038_remove_employee_more_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_more_model',
            name='ica_agreement',
            field=models.FileField(blank=True, null=True, upload_to='HR/'),
        ),
        migrations.AddField(
            model_name='employee_more_model',
            name='signed_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='HR/'),
        ),
    ]
