# Generated by Django 5.0.1 on 2024-02-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0039_employee_more_model_ica_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_more_model',
            old_name='ica_agreement',
            new_name='ICA_agreement',
        ),
    ]
