# Generated by Django 5.0.1 on 2024-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0043_previous_page_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Previous_Page_model',
        ),
        migrations.AddField(
            model_name='employee',
            name='prev_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
    ]
