# Generated by Django 5.0.1 on 2024-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0045_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney_notes_model',
            name='follow_up_completed',
            field=models.BooleanField(default=False, verbose_name='Follow-up'),
        ),
    ]
