# Generated by Django 5.0.1 on 2024-02-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0046_attorney_notes_model_follow_up_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='follow_up_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.CreateModel(
            name='To_Do_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='02/16/2024', max_length=25, null=True, verbose_name='Review Date')),
                ('due_date', models.DateField(blank=True, max_length=25, null=True, verbose_name='Review Date')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('document', models.FileField(blank=True, null=True, upload_to='Tasks/')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'To Do List',
                'verbose_name_plural': 'To Do List',
            },
        ),
    ]
