# Generated by Django 5.0.1 on 2024-02-17 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0047_alter_attorney_notes_model_follow_up_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney_notes_model',
            name='date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='call_date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Call Date'),
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='qa_date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='to_do_model',
            name='date',
            field=models.DateField(blank=True, default='02/17/2024', max_length=25, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='to_do_model',
            name='due_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Due Date'),
        ),
        migrations.CreateModel(
            name='Metrics_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('Attrition Rate', 'Attrition Rate'), ('Call Timeliness', 'Call Timeliness'), ('Review Completion', 'Review Completion'), ('EA Completion', 'EA Completion'), ('Pro Se Answer Reviews', 'Pro Se Answer Reviews'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Disposition')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('document', models.FileField(blank=True, null=True, upload_to='Metrics/')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'Metrics',
                'verbose_name_plural': 'Metrics',
            },
        ),
    ]
