# Generated by Django 5.0.1 on 2024-02-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0048_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics_model',
            name='date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Metric Date'),
        ),
        migrations.AlterField(
            model_name='metrics_model',
            name='metric',
            field=models.CharField(choices=[('Attrition Rate', 'Attrition Rate'), ('Call Timeliness', 'Call Timeliness'), ('Review Completion', 'Review Completion'), ('EA Completion', 'EA Completion'), ('Pro Se Answer Reviews', 'Pro Se Answer Reviews'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Metric'),
        ),
    ]
