# Generated by Django 5.0.1 on 2024-02-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0050_metrics_model_other_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_model',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Value'),
        ),
    ]
