# Generated by Django 5.0.1 on 2024-02-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0051_alter_metrics_model_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_monitoring_model',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='call_monitoring_model',
            name='call_time',
        ),
        migrations.AddField(
            model_name='call_monitoring_model',
            name='call_datetime',
            field=models.DateTimeField(blank=True, max_length=25, null=True, verbose_name='Call Date'),
        ),
    ]
