# Generated by Django 5.0.1 on 2024-02-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0053_remove_call_monitoring_model_call_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_model',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Value'),
        ),
    ]
