# Generated by Django 5.0.1 on 2024-02-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0054_alter_metrics_model_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics_model',
            name='date',
            field=models.DateField(max_length=25, null=True, verbose_name='Metric Date'),
        ),
    ]
