# Generated by Django 5.0.1 on 2024-02-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0055_alter_metrics_model_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_requests_model',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='hr_requests_model',
            name='denied',
        ),
        migrations.AddField(
            model_name='hr_requests_model',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=25, null=True, verbose_name='Request Status'),
        ),
    ]
