# Generated by Django 5.0.1 on 2024-02-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0056_remove_hr_requests_model_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_requests_model',
            name='reasoning',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decision Reasoning'),
        ),
    ]
