# Generated by Django 5.0.1 on 2024-02-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0057_alter_hr_requests_model_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_requests_model',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=25, null=True, verbose_name='Request Status'),
        ),
    ]
