# Generated by Django 5.0.1 on 2024-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0061_employee_id_employee_more_model_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee_more_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='call_monitoring_model',
            name='reviewer',
            field=models.CharField(choices=[], max_length=50, null=True, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(blank=True, choices=[], default='', max_length=50, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_abbrev',
            field=models.CharField(choices=[], max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='employee_more_model',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='hr_requests_model',
            name='decision_manager',
            field=models.CharField(choices=[], max_length=50, null=True, verbose_name='Decision Manager'),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='delivered_by',
            field=models.CharField(choices=[], max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='search_attorneys_model',
            name='search_state',
            field=models.CharField(blank=True, choices=[], max_length=25, null=True, verbose_name='Search by State'),
        ),
    ]
