# Generated by Django 5.0.1 on 2024-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0062_remove_employee_id_remove_employee_more_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
