# Generated by Django 5.0.1 on 2024-02-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0030_alter_attorney_notes_model_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding_Detail_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_job', models.BooleanField(default=False, verbose_name='pause_job')),
                ('send_onboarding_email', models.BooleanField(default=False, verbose_name='Send onboarding email')),
                ('add_to_spreadsheet', models.BooleanField(default=False, verbose_name='Add to spreadsheet')),
                ('save_license', models.BooleanField(default=False, verbose_name='Save Bar License')),
                ('bar_license_document', models.FileField(blank=True, null=True, upload_to='Bar/')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Save Bar License')),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attorneys.employee')),
            ],
            options={
                'verbose_name': 'Onboarding Detail',
                'verbose_name_plural': 'Onboarding Detail',
            },
        ),
    ]
