# Generated by Django 5.0.1 on 2024-02-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding_detail_model',
            name='pause_job',
            field=models.BooleanField(default=False, verbose_name='Pause job posting; review and save pending resumes (if needed)'),
        ),
        migrations.AlterField(
            model_name='onboarding_detail_model',
            name='send_onboarding_email',
            field=models.BooleanField(default=False, verbose_name='Send onboarding email to '),
        ),
    ]
