# Generated by Django 5.0.1 on 2024-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboarding_detail_model_pause_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='send_spreadsheet',
            field=models.BooleanField(default=False, verbose_name='Send spreadsheet'),
        ),
        migrations.AlterField(
            model_name='onboarding_detail_model',
            name='send_onboarding_email',
            field=models.BooleanField(default=False, verbose_name='Send onboarding email to: '),
        ),
    ]
