# Generated by Django 5.0.1 on 2024-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_remove_onboarding_detail_model_bar_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='add_employee_more',
            field=models.BooleanField(default=False, verbose_name='Add additional employee data'),
        ),
    ]
