# Generated by Django 5.0.1 on 2024-02-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_onboarding_detail_model_add_employee_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding_detail_model',
            old_name='add_employee_more',
            new_name='add_attorney_more',
        ),
    ]
