# Generated by Django 5.0.1 on 2024-02-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_rename_add_employee_more_onboarding_detail_model_add_attorney_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='attach_copy_letter',
            field=models.BooleanField(default=False, verbose_name='Attach copy of offer letter'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='employee_referral_form',
            field=models.BooleanField(default=False, verbose_name='Attach employee referral program form'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='include_note',
            field=models.BooleanField(default=False, verbose_name='Include Note'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='notify_Huron',
            field=models.BooleanField(default=False, verbose_name='Notify Laura Pina of new attorney start date'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='puzzle_form',
            field=models.BooleanField(default=False, verbose_name='Complete Puzzle HR Form'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='return_ICA',
            field=models.BooleanField(default=False, verbose_name='Return fully executed ICAs to attorney'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='save_offer_letter',
            field=models.BooleanField(default=False, verbose_name='Save Offer Letter'),
        ),
    ]
