# Generated by Django 5.0.1 on 2024-02-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_onboarding_detail_model_attach_copy_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='attorney_pp_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Touch Base Date'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='attorney_pp_training',
            field=models.BooleanField(default=False, verbose_name='Schedule Attorney Policies and Procedures Training'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='intro_training',
            field=models.BooleanField(default=False, verbose_name='Schedule firm introduction training'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='intro_training_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Intro Training Date'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='salesforce_training',
            field=models.BooleanField(default=False, verbose_name='Schedule Salesforce and Servicing Training'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='salesforce_training_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Salesforce and Servicing Training Date'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='script_training',
            field=models.BooleanField(default=False, verbose_name='Schedule Individual Script Training'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='script_training_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Individual Script Training Date'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='send_pp_docs',
            field=models.BooleanField(default=False, verbose_name='Send onboarding documents to attorney'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='send_software_docs',
            field=models.BooleanField(default=False, verbose_name='Send software documents to attorney'),
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='touch_base_meeting',
            field=models.BooleanField(default=False, verbose_name='Schedule Touch Base Meeting'),
        ),
    ]
