# Generated by Django 5.0.1 on 2024-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_onboarding_detail_model_attorney_pp_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding_detail_model',
            old_name='touch_base_meeting',
            new_name='touchbase_meeting',
        ),
        migrations.AddField(
            model_name='onboarding_detail_model',
            name='touchbase_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Touch Base Date'),
        ),
        migrations.AlterField(
            model_name='onboarding_detail_model',
            name='attorney_pp_date',
            field=models.DateField(blank=True, max_length=25, null=True, verbose_name='Individual Script Training Date'),
        ),
    ]
