# Generated by Django 5.0.1 on 2024-02-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_rename_touch_base_meeting_onboarding_detail_model_touchbase_meeting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onboarding_Detail_Model',
        ),
    ]
